### ISSUE TITLE
Adding few new temperature sensors causes error.

### ISSUE THREAD

**Issue by znakednady** [SynTexDZN/homebridge-syntex-knx#1]
Is there a limitation to number of devices?

I got this error when I added few temperature sensors.
When reduced number, all goes through.
<img width="710" alt="error" src="https://user-images.githubusercontent.com/97736836/149510875-555cf4c2-8421-43c4-98d3-f32e9a2726bb.PNG">

**Comment by SynTexDZN** [comment]
Hey. There is a limit of HomeBridge in common that you can only add 256 devices per instance but I think there would be another error. Could you please send in the 'accessory' part of the plugin configuration?

**Comment by znakednady** [comment]
Here is the current from the plugin (working one)
(In addition to this there are multiple devices in use that are not in config, because of this error added some devices still even when the error occured).

The errors started only when I did add multiple of those temperature sensors, before that no errors - the system being live and kicking 2 months.

`
{
    "platform": "SynTexKNX",
    "name": "SynTexKNX",
    "baseDirectory": "/var/homebridge/SynTex",
    "ip": "X",
    "port": X,
    "language": "us",
    "debug": false,
    "accessories": [
        {
            "id": "knx_status_kotona",
            "name": "Kotona Tila",
            "services": [
                {
                    "address": {
                        "status": "2/3/11",
                        "control": "2/3/1"
                    },
                    "type": "switch"
                }
            ]
        },
        {
            "id": "knx_status_tunnelma",
            "name": "Tunnelma Tila",
            "services": [
                {
                    "address": {
                        "status": "2/3/15",
                        "control": "2/3/5"
                    },
                    "type": "switch"
                }
            ]
        },
        {
            "id": "knx_status_ilta",
            "name": "Ilta Tila",
            "services": [
                {
                    "address": {
                        "status": "2/3/12",
                        "control": "2/3/2"
                    },
                    "type": "switch"
                }
            ]
        },
        {
            "id": "knx_status_poissa",
            "name": "Poissa Tila",
            "services": [
                {
                    "address": {
                        "status": "2/3/16",
                        "control": "2/3/6"
                    },
                    "type": "switch"
                }
            ]
        },
        {
            "id": "knx_status_aamu",
            "name": "Aamu Tila",
            "services": [
                {
                    "address": {
                        "status": "2/3/13",
                        "control": "2/3/3"
                    },
                    "type": "switch"
                }
            ]
        },
        {
            "id": "knx_status_siivous",
            "name": "Siivous Tila",
            "services": [
                {
                    "address": {
                        "status": "2/3/17",
                        "control": "2/3/7"
                    },
                    "type": "switch"
                }
            ]
        },
        {
            "id": "knx_status_yo",
            "name": "Yö Tila",
            "services": [
                {
                    "address": {
                        "status": "2/3/14",
                        "control": "2/3/4"
                    },
                    "type": "switch"
                }
            ]
        },
        {
            "id": "knx-ylakerta-eteinen-seina",
            "name": "Eteinen Seinä",
            "services": [
                {
                    "address": {
                        "status": "1/0/27",
                        "control": "1/0/26"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ylakerta-eteinen-katto",
            "name": "Eteinen Katto",
            "services": [
                {
                    "address": {
                        "status": "1/4/26",
                        "control": "1/4/25"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ylakerta-mh-katto",
            "name": "Makuuhuone Katto",
            "services": [
                {
                    "address": {
                        "status": "1/0/17",
                        "control": "1/0/16"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ylakerta-mh-led",
            "name": "Makuuhuone Led",
            "services": [
                {
                    "address": {
                        "status": "1/4/66",
                        "control": "1/4/65"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ylakerta-mh-yp-antti",
            "name": "Yöpöytä Antti",
            "services": [
                {
                    "address": {
                        "status": "1/0/37",
                        "control": "1/0/36"
                    },
                    "type": "outlet"
                }
            ]
        },
        {
            "id": "knx-ylakerta-mh-yp-ansku",
            "name": "Yöpöytä Ansku",
            "services": [
                {
                    "address": {
                        "status": "1/0/39",
                        "control": "1/0/38"
                    },
                    "type": "outlet"
                }
            ]
        },
        {
            "id": "knx-ylakerta-mh-vaatehuone",
            "name": "Makuuhuone Vaatehuone",
            "services": [
                {
                    "address": {
                        "status": "1/0/19",
                        "control": "1/0/18"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-makuuhuone-vh-lasnaolo",
            "name": "Makuuhuone VH Läsnäolo",
            "services": [
                {
                    "address": {
                        "status": "0/4/41",
                        "control": "0/4/41"
                    },
                    "type": "occupancy"
                }
            ]
        },
        {
            "id": "knx-ylakerta-emma-katto",
            "name": "Emman Huone Katto",
            "services": [
                {
                    "address": {
                        "status": "1/1/16",
                        "control": "1/1/15"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ylakerta-emma-led",
            "name": "Emman Huone Led",
            "services": [
                {
                    "address": {
                        "status": "1/4/31",
                        "control": "1/4/30"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ylakerta-emma-yo",
            "name": "Emman Huone Yövalo",
            "services": [
                {
                    "address": {
                        "status": "1/0/41",
                        "control": "1/0/40"
                    },
                    "type": "outlet"
                }
            ]
        },
        {
            "id": "knx-ylakerta-nopo-led",
            "name": "Nöpön Huone Led",
            "services": [
                {
                    "address": {
                        "status": "1/4/36",
                        "control": "1/4/35"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ylakerta-nopo-yo",
            "name": "Nöpön Huone Yövalo",
            "services": [
                {
                    "address": {
                        "status": "1/0/43",
                        "control": "1/0/42"
                    },
                    "type": "outlet"
                }
            ]
        },
        {
            "id": "knx-ylakerta-wc-peili",
            "name": "Yläkerran WC Peili",
            "services": [
                {
                    "address": {
                        "status": "1/0/13",
                        "control": "1/0/12"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ylakerta-wc-katto",
            "name": "Yläkerran WC Katto",
            "services": [
                {
                    "address": {
                        "status": "1/4/92",
                        "control": "1/4/91"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ylakerta-wc-lasnaolo",
            "name": "Yläkerran WC Liiketunnistin",
            "services": [
                {
                    "address": {
                        "status": "0/4/31",
                        "control": "0/4/31"
                    },
                    "type": "occupancy"
                }
            ]
        },
        {
            "id": "knx-ylakerta-keittio-katto",
            "name": "Keittiö Katto",
            "services": [
                {
                    "address": {
                        "status": "1/4/41",
                        "control": "1/4/40"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ylakerta-keittio-lednauha",
            "name": "Keittiö Led",
            "services": [
                {
                    "address": {
                        "status": "1/4/117",
                        "control": "1/4/116"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ylakerta-keittio-poyta",
            "name": "Keittiö Pöytä",
            "services": [
                {
                    "address": {
                        "status": "1/1/6",
                        "control": "1/1/5"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ylakerta-keittio-tiskiallas",
            "name": "Keittiö Tiskiallas",
            "services": [
                {
                    "address": {
                        "status": "1/0/1",
                        "control": "1/0/0"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ylakerta-keittio-ikkunarasia",
            "name": "Keittiö Kattopistoke",
            "services": [
                {
                    "address": {
                        "status": "1/0/29",
                        "control": "1/0/28"
                    },
                    "type": "outlet"
                }
            ]
        },
        {
            "id": "knx-ylakerta-olohuone-ikkunarasia",
            "name": "Olohuone Kattopistoke",
            "services": [
                {
                    "address": {
                        "status": "1/0/23",
                        "control": "1/0/22"
                    },
                    "type": "outlet"
                }
            ]
        },
        {
            "id": "knx-ylakerta-olohuone-alarasia",
            "name": "Olohuone Alapistoke",
            "services": [
                {
                    "address": {
                        "status": "1/0/45",
                        "control": "1/0/44"
                    },
                    "type": "outlet"
                }
            ]
        },
        {
            "id": "knx-ylakerta-olohuone-katto",
            "name": "Olohuone Katto",
            "services": [
                {
                    "address": {
                        "status": "1/0/25",
                        "control": "1/0/24"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ylakerta-olohuone-led",
            "name": "Olohuone Led",
            "services": [
                {
                    "address": {
                        "status": "1/4/56",
                        "control": "1/4/55"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ylakerta-oh-lasnaolo",
            "name": "Olohuone Liiketunnistin",
            "services": [
                {
                    "address": {
                        "status": "0/4/51",
                        "control": "0/4/51"
                    },
                    "type": "occupancy"
                }
            ]
        },
        {
            "id": "knx-ylakerta-portaat-led",
            "name": "Portaat Led",
            "services": [
                {
                    "address": {
                        "status": "1/4/102",
                        "control": "1/4/101"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ylakerta-portaat-katto",
            "name": "Portaat Katto",
            "services": [
                {
                    "address": {
                        "status": "1/1/1",
                        "control": "1/1/0"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ylakerta-portaat-seina",
            "name": "Portaat Seinä",
            "services": [
                {
                    "address": {
                        "status": "1/0/21",
                        "control": "1/0/20"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-alakerta-aula-led",
            "name": "Aula Led",
            "services": [
                {
                    "address": {
                        "status": "1/4/107",
                        "control": "1/4/106"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-alakerta-aula-katto",
            "name": "Aula Katto",
            "services": [
                {
                    "address": {
                        "status": "1/4/51",
                        "control": "1/4/50"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-alakerta-aula-lasnaolo",
            "name": "Aula Liiketunnistin",
            "services": [
                {
                    "address": {
                        "status": "0/4/11",
                        "control": "0/4/11"
                    },
                    "type": "occupancy"
                }
            ]
        },
        {
            "id": "knx-alakerta-vierashuone-katto",
            "name": "Vierashuone Katto",
            "services": [
                {
                    "address": {
                        "status": "1/1/11",
                        "control": "1/1/10"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-alakerta-Vierashuone-led",
            "name": "Vierashuone Led",
            "services": [
                {
                    "address": {
                        "status": "1/4/21",
                        "control": "1/4/20"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-alakerta-vierashuone-yo",
            "name": "Vierashuone Yövalo",
            "services": [
                {
                    "address": {
                        "status": "1/0/35",
                        "control": "1/0/34"
                    },
                    "type": "outlet"
                }
            ]
        },
        {
            "id": "knx-alakerta-khh-led",
            "name": "Kodinhoitohuone Led",
            "services": [
                {
                    "address": {
                        "status": "1/4/112",
                        "control": "1/4/111"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-alakerta-khh-poyta",
            "name": "Kodinhoitohuone Pöytä",
            "services": [
                {
                    "address": {
                        "status": "1/0/3",
                        "control": "1/0/2"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-alakerta-khh-katto",
            "name": "Kodinhoitohuone Katto",
            "services": [
                {
                    "address": {
                        "status": "1/4/11",
                        "control": "1/4/10"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-alakerta-khh-lasnaolo",
            "name": "Kodinhoitohuone Liiketunnistin",
            "services": [
                {
                    "address": {
                        "status": "0/4/21",
                        "control": "0/4/21"
                    },
                    "type": "occupancy"
                }
            ]
        },
        {
            "id": "knx-alakerta-pesuhuone-katto",
            "name": "Pesuhuone Katto",
            "services": [
                {
                    "address": {
                        "status": "1/4/6",
                        "control": "1/4/5"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-alakerta-sauna-seina",
            "name": "Sauna Seinä",
            "services": [
                {
                    "address": {
                        "status": "1/0/9",
                        "control": "1/0/8"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-alakerta-sauna-lauteet",
            "name": "Sauna Lauteet",
            "services": [
                {
                    "address": {
                        "status": "1/0/11",
                        "control": "1/0/10"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-alakerta-wc-katto",
            "name": "Alakerta WC Katto",
            "services": [
                {
                    "address": {
                        "status": "1/4/82",
                        "control": "1/4/81"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-alakerta-wc-koriste",
            "name": "Alakerta WC Koriste",
            "services": [
                {
                    "address": {
                        "status": "1/0/5",
                        "control": "1/0/4"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-alakerta-wc-peili",
            "name": "Alakerta WC Peili",
            "services": [
                {
                    "address": {
                        "status": "1/0/7",
                        "control": "1/0/6"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-alakerta-wc-lasnaolo",
            "name": "Alakerran WC Liiketunnistin",
            "services": [
                {
                    "address": {
                        "status": "0/4/1",
                        "control": "0/4/1"
                    },
                    "type": "occupancy"
                }
            ]
        },
        {
            "id": "knx-alakerta-varasto",
            "name": "Sisävarasto",
            "services": [
                {
                    "address": {
                        "status": "1/4/1",
                        "control": "1/4/0"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-alakerta_mh_katto",
            "name": "Mediahuone Katto",
            "services": [
                {
                    "address": {
                        "status": "1/4/16",
                        "control": "1/4/15"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-alakerta_mh_etuled",
            "name": "Mediahuone Etu Led",
            "services": [
                {
                    "address": {
                        "status": "1/4/61",
                        "control": "1/4/60"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-alakerta_mh_takaled",
            "name": "Mediahuone Taka Led",
            "services": [
                {
                    "address": {
                        "status": "1/4/122",
                        "control": "1/4/121"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-alakerta_mh_pistoke",
            "name": "Mediahuone Pistorasia",
            "services": [
                {
                    "address": {
                        "status": "1/0/33",
                        "control": "1/0/32"
                    },
                    "type": "outlet"
                }
            ]
        },
        {
            "id": "knx-kuntosali-katto",
            "name": "Kuntosalin Katto",
            "services": [
                {
                    "address": {
                        "status": "1/4/71",
                        "control": "1/4/72"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-kuntosali-seina",
            "name": "Kuntosalin Seinä",
            "services": [
                {
                    "address": {
                        "status": "1/4/127",
                        "control": "1/4/126"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-kuntosali-varasto",
            "name": "Kuntosalin Varasto",
            "services": [
                {
                    "address": {
                        "status": "1/4/132",
                        "control": "1/4/131"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-kuntosali-puhallin",
            "name": "Kuntosalin Puhallin",
            "services": [
                {
                    "address": {
                        "status": "1/0/189",
                        "control": "1/0/189"
                    },
                    "type": "switch"
                }
            ]
        },
        {
            "id": "knx-kuntosali-lasnaolo",
            "name": "Kuntosali Läsnäolo",
            "services": [
                {
                    "address": {
                        "status": "0/4/61",
                        "control": "0/4/61"
                    },
                    "type": "occupancy"
                }
            ]
        },
        {
            "id": "knx-kuntosali-varasto-lasnaolo",
            "name": "Kuntosali Varasto Läsnäolo",
            "services": [
                {
                    "address": {
                        "status": "0/4/71",
                        "control": "0/4/71"
                    },
                    "type": "occupancy"
                }
            ]
        },
        {
            "id": "knx-parveke-kattovalo",
            "name": "Parveke Kattovalo",
            "services": [
                {
                    "address": {
                        "status": "1/0/61",
                        "control": "1/0/60"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-parveke-seina",
            "name": "Parveke Seinävalo",
            "services": [
                {
                    "address": {
                        "status": "1/0/63",
                        "control": "1/0/62"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-terassi-katto",
            "name": "Terassi Kattovalo",
            "services": [
                {
                    "address": {
                        "status": "1/0/53",
                        "control": "1/0/53"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-terassi-upotetut",
            "name": "Terassi Upotetut",
            "services": [
                {
                    "address": {
                        "status": "1/0/55",
                        "control": "1/0/54"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ulkoseinat-yläkerta",
            "name": "Ulkoseinä Yläkerta",
            "services": [
                {
                    "address": {
                        "status": "1/0/65",
                        "control": "1/0/64"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ulkoseinat-alakerta",
            "name": "Ulkoseinä Alakerta",
            "services": [
                {
                    "address": {
                        "status": "1/0/51",
                        "control": "1/0/50"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ulkoseinat-autokatos",
            "name": "Ulkoseinä Autokatos",
            "services": [
                {
                    "address": {
                        "status": "1/0/49",
                        "control": "1/0/48"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-ulkoseinat-etuovi",
            "name": "Ulkoseinä Etuovi",
            "services": [
                {
                    "address": {
                        "status": "1/0/67",
                        "control": "1/0/66"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-pihavalot-etupiha",
            "name": "Pihavalot Etupiha",
            "services": [
                {
                    "address": {
                        "status": "1/0/59",
                        "control": "1/0/58"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-pihavalot-takapiha",
            "name": "Pihavalot Takapiha",
            "services": [
                {
                    "address": {
                        "status": "1/0/57",
                        "control": "1/0/56"
                    },
                    "type": "led"
                }
            ]
        },
        {
            "id": "knx-autokatos-pistorasiat-vasen",
            "name": "Autokatos Vasen",
            "services": [
                {
                    "address": {
                        "status": "1/0/71",
                        "control": "1/0/70"
                    },
                    "type": "outlet"
                }
            ]
        },
        {
            "id": "knx-autokatos-pistorasiat-oikea",
            "name": "Autokatos Oikea",
            "services": [
                {
                    "address": {
                        "status": "1/0/69",
                        "control": "1/0/68"
                    },
                    "type": "outlet"
                }
            ]
        },
        {
            "id": "knx-other-lukot",
            "name": "Sähkölukot",
            "services": [
                {
                    "address": {
                        "status": "1/0/73",
                        "control": "1/0/72"
                    },
                    "type": "switch"
                }
            ]
        },
        {
            "id": "knx-other-takkatoiminto",
            "name": "Takkatoiminto",
            "services": [
                {
                    "address": {
                        "status": "1/0/99",
                        "control": "1/0/98"
                    },
                    "type": "switch"
                }
            ]
        },
        {
            "id": "knx-other-lammitys",
            "name": "Lämmitys",
            "services": [
                {
                    "address": {
                        "status": "1/3/85",
                        "control": "1/3/84"
                    },
                    "type": "switch"
                }
            ]
        },
        {
            "id": "knx-other-portaan-sulanapito",
            "name": "Portaan Sulanapito",
            "services": [
                {
                    "address": {
                        "status": "1/0/75",
                        "control": "1/0/74"
                    },
                    "type": "switch"
                }
            ]
        },
        {
            "id": "knx-other-ovi-impulssi-ak",
            "name": "Ovien Impulssi Alakerta",
            "services": [
                {
                    "address": {
                        "status": "0/2/4",
                        "control": "0/2/4"
                    },
                    "type": "contact"
                }
            ]
        },
        {
            "id": "knx-other-ovi-impulssi-yk",
            "name": "Ovien Impulssi Yläkerta",
            "services": [
                {
                    "address": {
                        "status": "0/2/5",
                        "control": "0/2/5"
                    },
                    "type": "contact"
                }
            ]
        },
        {
            "id": "knx-other-halytys-kosteus",
            "name": "Kosteushälytys",
            "services": [
                {
                    "address": {
                        "status": "0/2/3",
                        "control": "0/2/3"
                    },
                    "type": "contact"
                }
            ]
        },
        {
            "id": "knx-other-halytys-IV",
            "name": "IV-Hälytys",
            "services": [
                {
                    "address": {
                        "status": "0/1/0",
                        "control": "0/1/0"
                    },
                    "type": "contact"
                }
            ]
        },
        {
            "id": "knx-other-halytys-pumppu",
            "name": "Pumppaamo Hälytys",
            "services": [
                {
                    "address": {
                        "status": "0/1/2",
                        "control": "0/1/2"
                    },
                    "type": "contact"
                }
            ]
        },
        {
            "id": "knx-other-halytys-palo",
            "name": "Palohälytys",
            "services": [
                {
                    "address": {
                        "status": "0/2/2",
                        "control": "0/2/2"
                    },
                    "type": "contact"
                }
            ]
        },
        {
            "id": "knx-other-halytys-murto",
            "name": "Murtohälytys",
            "services": [
                {
                    "address": {
                        "status": "0/2/1",
                        "control": "0/2/1"
                    },
                    "type": "contact"
                }
            ]
        },
        {
            "id": "knx-other-halytys-murtotila",
            "name": "Murtojärjestelmän Tila",
            "services": [
                {
                    "address": {
                        "status": "0/2/0",
                        "control": "0/2/0"
                    },
                    "type": "contact"
                }
            ]
        },
        {
            "id": "knx-lampotila-mediahuone",
            "name": "Mediahuone Lämpötila",
            "services": [
                {
                    "address": {
                        "status": "1/3/39"
                    },
                    "type": "temperature"
                }
            ]
        },
        {
            "id": "knx-lampotila-sisavarasto",
            "name": "Sisävarasto Lämpötila",
            "services": [
                {
                    "address": {
                        "status": "1/3/32"
                    },
                    "type": "temperature"
                }
            ]
        },
        {
            "id": "knx-lampotila-vierashuone",
            "name": "Vierashuone Lämpötila",
            "services": [
                {
                    "address": {
                        "status": "1/3/46"
                    },
                    "type": "temperature"
                }
            ]
        },
        {
            "id": "knx-lampotila-khh",
            "name": "Kodinhoitohuone Lämpötila",
            "services": [
                {
                    "address": {
                        "status": "0/3/2"
                    },
                    "type": "temperature"
                }
            ]
        },
        {
            "id": "knx-lampotila-sauna",
            "name": "Sauna Lämpötila",
            "services": [
                {
                    "address": {
                        "status": "0/3/0"
                    },
                    "type": "temperature"
                }
            ]
        },
        {
            "id": "knx-lampotila-makuuhuone",
            "name": "Makuuhuone Lämpötila",
            "services": [
                {
                    "address": {
                        "status": "1/3/4"
                    },
                    "type": "temperature"
                }
            ]
        },
        {
            "id": "knx-lampotila-olohuone",
            "name": "Olohuone Lämpötila",
            "services": [
                {
                    "address": {
                        "status": "1/3/25"
                    },
                    "type": "temperature"
                }
            ]
        }
    ]
}`

**Comment by znakednady** [comment]
Hello, I actually found the problem. I had double ID for device. So sorry and thanks :).
You are doing great job with the package - please continue great work!
