### ISSUE TITLE
Blinds configuration

### ISSUE THREAD

**Issue by lodoss5** [SynTexDZN/homebridge-syntex-knx#14]
**Describe the bug**
I installed latest beta. Trying to configure my blinds, the current position does not seem to be sent in HomeKit and in HomeKit I can give order to go up or down but giving a specific open % does not work, the blind move but sometimes in the wrong way.

**Expected behavior**
0 is when blinds are full up, 100 when full down in KNX.
100 is when blinds are full up, 0 when full down in HomeKit.

**Config**
{
            "id": "KNX-Salon-Store1",
            "name": "KNX-Store1",
            "services": [
                {
                    "address": {
                        "status": "2/1/30",
                        "control": "2/0/30"
                    },
                    "delay": {
                        "up": 26000,
                        "down": 24000
                    },
                    "type": "blind",
                    "name": "Up / Down"
                },
                {
                    "address": {
                        "status": "2/2/30",
                        "control": "2/2/30"
                    },
                    "type": "switch",
                    "name": "Stop"
                }
            ]
        }

Clarification on my KNX installation :
1 bit - 2/0/30 : to control up/down
1 bit - 2/2/30 : to stop
05.001 scale - 2/1/30 : position status

Thank you so much for your work, it is really amazing :)

**Comment by marabknx** [comment]
I also tried to implement the blinds in HomeKit. The logic is inverted, but the Accessory Config „inverted“ seems to do not work on KNX datapoints, e.g. 5.001

Here is my configuration of blinds with control of percentages:

> 
                    "id": "EssenSonnenblende",
                    "name": "Jalousie Essen",
                    "services": [
                        {
                            "datapoint": "5.001",
                            "address": {
                                "status": "2/7/14",
                                "control": "2/7/15"
                            },
                            "delay": {
                                "up": 55000,
                                "down": 55000
                            },
                            "type": "blind",
                            "name": "Jalousie",
                            „inverted“: true
                        }]

**Comment by SynTexDZN** [comment]
Hey @lodoss5 and @marabknx,
I tried to recreate the issue with the following config:

```json
{
	"id": "knx1",
	"name": "SynTex Blind",
	"services": [
		{
			"datapoint": "5.001",
			"address": {
				"status": "10/0/225",
				"control": "10/0/225"
			},
			"type": "blind"
		}
	]
}
```

This config worked fine for me.
Do you still get unexpected behavior when sending a blind position to the bus?
Are you both using the newest beta for this?

**Comment by marabknx** [comment]
@SynTexDZN 
I am still using a similar configuration as you presented in your comment. The problem is not to send blind positions - this is working fine.
My problem is that HomeKit sees the blinds closed with 100% and I want to have 100% for blinds are opened completely. Therefore I tried to add the inverted command to the configuration as you can see in my configuration. Then the blind/configuration will not work anymore. (I have not used the latest beta)

Could you please try the following configuration to see the problem:
```
{
	"id": "knx1",
	"name": "SynTex Blind",
	"services": [
		{
			"datapoint": "5.001",
			"address": {
				"status": "10/0/225",
				"control": "10/0/225"
			},
			"type": "blind",
			"inverted": true
		}
	]
}
```

**Comment by marabknx** [comment]
Now I tried the new beta v1.0.3-b11 and it works also with the inverted logic.
