### ISSUE TITLE
Variable light setting

### ISSUE THREAD

**Issue by Dvid72** [SynTexDZN/homebridge-syntex-knx#16]
Hello and thank you for the work !!!

Sorry but I am unable to set variable lighting with the plugin ! Do you have an example of config.js please ?

I have as info :
ON/OFF : Write address & Read address
Position : Write Address & Read Address

Thank you, sincerely.

**Comment by Dvid72** [comment]
HELLO,

I am using homebridge-syntex-knx v1.0.2!
THANKS

**Comment by SynTexDZN** [comment]
Okay then the issue should be solved. I'm updating the README frequently that it includes the newest features of the current beta but that can be some times confusing.

You can install the newest beta with 'sudo npm install -g homebridge-syntex-knx@1.0.3-b11'

~ **SynTex**
