### ISSUE TITLE
Error EHOSTUNREACH and ETIMEDOUT

### ISSUE THREAD

**Issue by marabknx** [SynTexDZN/homebridge-syntex-knx#17]
**Describe the bug**
The Homebridge Protocol shows Error Messages, but initially in autumn 2022 they do not appear.

**Expected behavior**
I am confused with a configuration that includes error messages and I would like to resolve it.

**Config**
>    "platform": "SynTexKNX",
            "name": "SynTexKNX",
            "baseDirectory": "/volume1/homebridge/SynTex",
            "ip": "192.168.178.30",
            "options": {
                "port": 3671,
                "language": "de",
                "disablePreload": false
            },
            "log": {
                "error": true,
                "warn": true,
                "info": true,
                "read": false,
                "update": true,
                "success": true,
                "debug": true
            },

**Logs**
> [37m[3/23/2023, 8:02:02 AM] [39mHomebridge v1.6.0 (HAP v0.11.0) (Homebridge) is running on port 51746.
[SynTexKNX] [31m[ERROR][0m [automation.json] konnte nicht gelesen werden!
[Error: ENOENT: no such file or directory, open '/volume1/homebridge/SynTex/automation/automation.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/volume1/homebridge/SynTex/automation/automation.json'
}
[SynTexKNX] [35m[DEBUG][0m KNX IP Gateway getrennt!
[SynTexKNX] [35m[DEBUG][0m KNX IP Gateway getrennt!
…
[SynTexKNX] [35m[DEBUG][0m GET [2/4/10] --> [7]
[SynTexKNX] [35m[DEBUG][0m GET [4/4/3] --> [0]
[SynTexKNX] [35m[DEBUG][0m GET [0/5/0] --> [136]
[SynTexKNX] [35m[DEBUG][0m GET [4/4/2] --> [1]
[SynTexKNX] [35m[DEBUG][0m GET [5/1/4] --> [0]
**[SynTexKNX] [31m[ERROR][0m Fehler: connect ETIMEDOUT 94.31.106.127:8800
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)**
[SynTexKNX] [35m[DEBUG][0m GET [4/4/1] --> [0]
…
[SynTexKNX] [35m[DEBUG][0m GET [4/4/12] --> [7]
[SynTexKNX] [35m[DEBUG][0m >>> [SynTexKNX] updateState ["5/0/1"] {"value":1978.88}
[SynTexKNX] [35m[DEBUG][0m <<< [SynTexKNX] updateState ["5/0/1"] {"value":1978.88}
[SynTexKNX] [96m[UPDATE][0m HomeKit Status von [Helligkeit Süd] geändert zu [1978.88] ( WetterstationIlluOutside )
[SynTexKNX] [35m[DEBUG][0m GET [5/0/1] --> [62]
**[SynTexKNX] [31m[ERROR][0m Fehler: connect EHOSTUNREACH 94.31.106.127:8800
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)**

**Screenshots**
N/A

**More Information**
 - OS: Synology DSM
 - Node Version V16.14.2

**Additional context**
I have not configured automation.json, so this error on startup is valid.

**Comment by SynTexDZN** [comment]
Hey @marabknx,
I'm currently working on a fix for this issue. If it's only the error message that confuses you I could soon publish a new beta for this. Otherwise the error should disappear the coming weeks after I fixed it.

~ **SynTex**

**Comment by SynTexDZN** [comment]
A already published a new beta with a fix for this :)
You can install it if you want with `sudo npm install -g homebridge-syntex-knx@1.0.3-b11`

~ **SynTex**
