### ISSUE TITLE
SynTex KNX Support for Blinds

### ISSUE THREAD

**Issue by miobio** [SynTexDZN/homebridge-syntex-knx#4]
Hi, I love your project and I am using it at home but it is lacking of blinds support. I saw it is in your TODO list, I am willing to support your work!

Please consider implementing this feature :-)

Another missing thing is dimmed lights but I don't have dimmed lights a t home so... 

Thanks for considering my request

**Comment by miobio** [comment]
Thank you very much! Appreciated. Those at my home express their position using 0...100 scale with load absorption detection. I believe those would be easier to implement in your plugin as they just need a % value i.e.

`Relative value | EIS 6 | DPT 5.yyy | Percentage, position, brightness, ... | 0 ... 100% | 1 Byte | 8-bit unsigned value`

**Comment by SynTexDZN** [comment]
Blinds have been added to the KNX plugin :)

~ **SynTex**
