### ISSUE TITLE
HomeKit Switch type problem with Siri when using lights

### ISSUE THREAD

**Issue by miobio** [SynTexDZN/homebridge-syntex-knx#5]
Hi, I don't know if I'm doing something wrong or what. I created a "Multi Accessory" item with some type switch entries in it. Unfortunately Siri seems not to identify these as lights and if I say "Hey Siri, switch on light XYZ" Siri says it does not recognise such accessory.

In order for Siri to work I have to use a generic term such as "Hey Siri, switch on accessory XYZ". With other platforms (e.g. Philips HUE) Siri identifies these accessories as lights correctly and I can interact with them using the form "Hey Siri, switch on light XYZ"

Here's a short extract of my config.json I don't know whether there is a HomeKit property to be set in order for this to work correctly or maybe is the multi accessory that is creating issues.

{
            "platform": "SynTexKNX",
            "baseDirectory": "/var/lib/homebridge/SynTex",
            "ip": "XXX.XXX.XXX.XXX",
            "options": {
                "port": 1714,
                "language": "en",
                "debug": false
            },
            "accessories": [
                {
                    "id": "Group Addresses X",
                    "name": "kitchen",
                    "services": [
                        {
                            "address": {
                                "status": "X/Y/Z",
                                "control": "X/Y1/Z"
                            },
                            "type": "switch",
                            "name": "Entrance door"
                        },
                        {
                            "address": {
                                "status": "X/Y/Z",
                                "control": "X/Y1/Z"
                            },
                            "type": "switch",
                            "name": "Door 3"
                        }

**Comment by SynTexDZN** [comment]
Hey @miobio,
when defining a service as a switch Siri doesn't identify them as a light.
When changing the type to `"type": "led"` your problem should be solved.
You could also try saying `Hey Siri, switch on XYZ` ( without `light` or `accessory` ) if there are no duplicates with your accessory / service names. Please let me know if that worked for you :)

~ **SynTex**

**Comment by miobio** [comment]
Ah! I thought about using type `"type": "led"`, I didn't do it before because my lights are not actually LED :-D but ok, I'll check what the behaviour is when I switch from `switch` to `led`.

Just to be sure, you believe the "Multi Accessory" is not the one creating problems here, correct?
