### ISSUE TITLE
Dimmable light

### ISSUE THREAD

**Issue by tillsteinbach** [SynTexDZN/homebridge-syntex-knx#8]
I need support for dimmable LED light. I found `// const DimmedBulbService = require('./accessories/dimmedBulb');` in the code. Any chance this is getting released any time soon?

**Comment by tillsteinbach** [comment]
Gibt es hier was neues?

**Comment by SynTexDZN** [comment]
Ja, gibt es. Nachdem ich vor kurzem das Automation Update veröffentlicht habe, ist das Licht Update das nächste. Dieses beinhaltet Dimmbare Lampen und RGB Lampen.

**Comment by tillsteinbach** [comment]
Habe gesehen dass es jetzt den "dimmer" service gibt. Der funktioniert aber noch nicht, oder?

**Comment by SynTexDZN** [comment]
Tatsächlich schon. Ich bin zwar noch nicht vollständig fertig mit dem Update, allerdings funktioniert der "Dimmer" Service schon ziemlich gut. Ich selbst benutze ihn schon in unserem KNX System.

**Comment by tillsteinbach** [comment]
Bei mir kommt da in der Home App dass das Gerät nicht unterstützt wird.

**Comment by SynTexDZN** [comment]
Welche Beta hast du installiert & wie sieht die Config zu deinem Dimmer aus?

**Comment by tillsteinbach** [comment]
Oh, ich habe garkeine beta installiert. Ich dachte dass da ein der 1.0.2 schon drin ist. Dann liegts daran :)

**Comment by tillsteinbach** [comment]
Noch eine Frage dazu: Ist es möglich zwei control Adressen einzustellen (Dimmwert und Schalten Ein/Aus)? Aktuell kann man zwar das device ausschalten, wenn man es aber wieder an machen möchte dann ist der Dimmwert 0. Ich habe probiert zwei Services anzulegen, aber das wird dann als zwei Lampen interpretiert.
